maslow:
  catalog:
    survey:
      - SECTION_IAMA:
          - IAMA
      - SECTION_TENANT_SITUATION:
          - EMPLOYMENT_SITUATION
          - MONTHLY_INCOME
          - RESIDENTIAL_SITUATION
          - MONTHLY_RENT
          - TENANT_RENT_OWED
          - TENANT_ZIP_CODE
      - SECTION_TENANT_DOCUMENTS:
          - IDENTIFICATION
          - PROOF_OF_INCOME
          - TAX_FORM
          - PROOF_OF_RESIDENCE
          - RENT_DUE
      - SECTION_LANDLORD_SITUATION:
          - UNITS_OWNED
          - UNITS_PAYING_RENT
          - LANDLORD_ZIP_CODE
