spring:
  application:
    name: maslow
  data:
    mongodb:
      database: FIND_SERVICES
  profiles:
    active: "@spring.profiles.active@"
    include: survey
  mongodb:
    embedded:
      version: 4.0.12
      features: NO_HTTP_INTERFACE_ARG,ONLY_WITH_SSL
  security:
    user:
      name: admin
      password: password

server:
  forward-headers-strategy: native
  port: 8081
  tomcat:
    accesslog:
      buffered: false
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rotate: true
      suffix: .log
    basedir: target/tomcat

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}

maslow:
  access:
    services-location: /tmp/maslow/services.json
